version: '3.8'

services:
  web:
    build: .
    container_name: django_crud_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
